---
  region: us-east-2
  servers:
    - instance_type: m5.2xlarge
      private_ip_addresses: [201]
      roles:
        - TxnGenerator

    - instance_type: r5.2xlarge
      private_ip_addresses: [101,102,103,104,105,106]
      roles:
        - ClusterMember

    - instance_type: m5.2xlarge
      private_ip_addresses: [222]
      roles:
        - Prometheus
        - ManCenter

  open_ports:
    TxnGenerator: [8511, 8888]
    ClusterMember: [8888, 7777, 5701]
    Prometheus: [9090, 3000]
    ManCenter: [8080]
